[grades]
1.rank = "F"
1.explanation = "Fail"
1.short_description = "Unusable"
1.long_description = "Model performance is unusable."

2.rank = "D"
2.explanation = "Below Reference"
2.short_description = "Below minimum quality reference system."
2.long_description = 'Model performance is below a "minimum quality reference system".'

3.rank = "C"
3.explanation = "Similar to Reference"
3.short_description = "At or above minimum quality reference system."
3.long_description = 'Model performance can be compared to a "minimum quality" reference system.'

4.rank = "B"
4.explanation = "Exceeds Reference"
4.short_description = "Equivalent to an untrained human."
4.long_description = "Model performance can be compared to an untrained human."

5.rank = "A"
5.explanation = "Near Human"
5.short_description = "Equivalent to a trained human."
5.long_description = "Model performance can be compared to a trained human."
