[bias_hazard]
name = "Bias"
description = "Explanation of hazard goes here"

[toxicity_hazard]
name = "Toxicity"
description = "Explanation of hazard goes here"

[safe_cae_hazard]
name = "Child Abuse and Exploitation"
description = "Explanation of hazard goes here"