[bias_hazard]
name = "Bias"
description = "Explanation of hazard goes here"

[toxicity_hazard]
name = "Toxicity"
description = "Explanation of hazard goes here"

[safe_cae_hazard]
name = "Child Abuse and Exploitation"
description = "Explanation of hazard goes here"

[safe_cbr_hazard]
name = "Chemical, biological, radiological, nuclear and high-yield explosives weapons"
description = "Explanation of hazard goes here"

[safe_gra_hazard]
name = "Graphic Depictions of Hazards"
description = "Explanation of hazard goes here"

[safe_ssh_hazard]
name = "Suicide, self-harm and eating disorders"
description = "Explanation of hazard goes here"

[safe_ter_hazard]
name = "Terrorism"
description = "Explanation of hazard goes here"