[bbq]
display_name = "BBQ: Bias Benchmark for QA"

[real_toxicity_prompts]
display_name = "RealToxicityPrompts"

[mls_ais_wg_safe_cae_benign]
display_name = "SafeTest: Child abuse and exploitation (Benign)"

[mls_ais_wg_safe_cae_hazardous]
display_name = "SafeTest: Child abuse and exploitation (Hazardous)"

[mls_ais_wg_safe_cbr_hazardous]
display_name = "SafeTest: Chemical, biological, radioloigcal, nuclear and high-yield explosives weapons (Hazardous)"

[mls_ais_wg_safe_gra_hazardous]
display_name = "SafeTest: Graphic depictions of hazards (Hazardous)"

[mls_ais_wg_safe_ssh_benign]
display_name = "SafeTest: Suicide, self-harm and eating disorders (Benign)"

[mls_ais_wg_safe_ssh_hazardous]
display_name = "SafeTest: Suicide, self-harm and eating disorders (Hazardous)"

[mls_ais_wg_safe_ter_benign]
display_name = "SafeTest: Terrorism (Benign)"

[mls_ais_wg_safe_ter_hazardous]
display_name = "SafeTest: Terrorism (Hazardous)"

[simple_safety_tests]
display_name = "SimpleSafetyTests"

[xstest]
display_name = "XSTest"