import copy
import pathlib

import pytest

from modelbench.hazards import Standards


@pytest.fixture
def standard():
    s = Standards(pathlib.Path(__file__).parent / "data" / "standards_base.json")
    return s


@pytest.fixture
def extra1():
    d = {
        "user": "pytest",
        "timestamp": "2024-12-18 05:52:01 UTC",
        "platform": "NeXTSTEP-3.3",
        "system": "Windows 3.11 For Workgroups",
        "node": "toaster",
        "python": "3.12.3",
    }
    return d


@pytest.fixture
def extra2():
    d = {
        "user": "pytest again",
        "timestamp": "2024-12-25 05:52:01 UTC",
        "platform": "RaspberryPi 4",
        "system": "System 7",
        "node": "streamer",
        "python": "3.12.4",
    }
    return d


def test_reload(standard):
    assert isinstance(standard.data, dict)
    assert isinstance(standard.metadata, dict)
    assert isinstance(standard.metadata["run_info"], dict)
    assert standard.metadata["NOTICE"] == "THIS FILE IS ONLY USED IN UNIT TESTS. THE NUMBERS ARE FAKE."


def test_append_run_info(standard, extra1, extra2):
    assert isinstance(standard.metadata["run_info"], dict)

    standard.append_run_info(extra1)
    assert isinstance(standard.metadata["run_info"], list)

    standard.append_run_info(extra2)
    assert isinstance(standard.metadata["run_info"], list)
    assert len(standard.metadata["run_info"]) == 3


def test_save(standard, tmp_path):
    assert isinstance(standard.metadata["run_info"], dict)
    new_file_path = tmp_path / "new_standard_1.json"
    new_standard = Standards(new_file_path, auto_load=False)
    new_standard.data = standard.data
    new_standard.metadata = standard.metadata
    new_standard.save("pytest")
    assert pathlib.Path.exists(new_file_path)
    new_standard.reload()
    assert new_standard.metadata["NOTICE"] == "This file is auto-generated by pytest; avoid editing it manually."


def test_save_notice(standard, extra1, extra2, tmp_path):
    new_standard = copy.deepcopy(standard)
    new_standard.path = tmp_path / "new_standard_2.json"
    assert new_standard.data == standard.data
    assert new_standard.metadata == standard.metadata

    new_standard.append_run_info(extra1)
    new_standard.append_run_info(extra2)
    new_standard.save("pytest again")
    new_standard.reload()

    assert isinstance(new_standard.metadata["run_info"], list)
    assert new_standard.metadata["NOTICE"] == "This file is auto-generated by pytest again; avoid editing it manually."
    assert len(new_standard.metadata["run_info"]) == 3
    assert new_standard.metadata["run_info"][0] == standard.metadata["run_info"]
    assert new_standard.metadata["run_info"][1] == extra1
    assert new_standard.metadata["run_info"][2] == extra2
