_GENERAL_V1_0 = "1.1"
_SECURITY_V1_0_2 = "1.0.2"

CURRENT_GENERAL_VERSION = _GENERAL_V1_0
CURRENT_SECURITY_VERSION = _SECURITY_V1_0_2
CURRENT_GENERAL_V_UNDER = CURRENT_GENERAL_VERSION.replace(".", "_")
CURRENT_SECURITY_V_UNDER = CURRENT_SECURITY_VERSION.replace(".", "_")
