from modelgauge.versions import CURRENT_GENERAL_VERSION, CURRENT_SECURITY_VERSION

SAFETY_ANNOTATOR_V1_1_UID = f"safety-v{CURRENT_GENERAL_VERSION}"
SAFETY_ANNOTATOR_V1_1_1_UID = "safety-dag-v1.1.1"
SECURITY_ANNOTATOR_V0_5_UID = "security-v0.5"
SECURITY_ANNOTATOR_V1_0_2_UID = f"security-v{CURRENT_SECURITY_VERSION}"
