from modelgauge.versions import CURRENT_GENERAL_VERSION, CURRENT_SECURITY_VERSION

SAFETY_ANNOTATOR_V1_1_UID = f"safety-v{CURRENT_GENERAL_VERSION}"
SECURITY_ANNOTATOR_V0_5_UID = "security-v0.5"
SECURITY_ANNOTATOR_V1_0_1_UID = f"security-v{CURRENT_SECURITY_VERSION}"
